import { test, expect } from '@playwright/test';

// ── Unauthenticated tests ────────────────────────────────────────────────────

test.describe('Auth header UI', () => {
  test('Sign In button is visible in unauthenticated state', async ({ page }) => {
    await page.goto('/');
    // layout.tsx calls auth() server-side — no session → renders SignInButton
    await expect(page.getByRole('button', { name: /sign in/i })).toBeVisible();
  });

  test('global header always shows brand name', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByRole('link', { name: /keyboard command center/i })).toBeVisible();
  });

  test('theme toggle is present alongside Sign In button', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByRole('button', { name: /toggle theme/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /sign in/i })).toBeVisible();
  });

  test('header Sign In button appears on all pages — app detail page', async ({ page }) => {
    await page.goto('/apps/vscode');
    // Sign In should appear in global header regardless of page
    await expect(page.getByRole('button', { name: /sign in/i })).toBeVisible();
  });

  // ── Middleware guard tests ───────────────────────────────────────────────
  // These confirm the protected route scaffolding (TASK-0021) returns 401.
  // The actual /api/favorites and /api/submissions routes don't exist yet
  // (TASK-0022 and Goal 8) — middleware intercepts the request before it
  // reaches any route handler.

  test('protected /api/favorites route returns 401 for unauthenticated request', async ({
    request,
  }) => {
    const res = await request.get('/api/favorites');
    expect(res.status()).toBe(401);
    const body = await res.json();
    expect(body).toHaveProperty('error', 'Unauthorized');
  });

  test('protected /api/submissions route returns 401 for unauthenticated request', async ({
    request,
  }) => {
    const res = await request.get('/api/submissions');
    expect(res.status()).toBe(401);
    const body = await res.json();
    expect(body).toHaveProperty('error', 'Unauthorized');
  });
});

// ── Authenticated tests ──────────────────────────────────────────────────────
// Uses a pre-built storageState cookie generated by e2e/auth-setup.ts (global setup).
// The cookie is a real Auth.js v5 JWE signed with the TEST_AUTH_SECRET that the dev
// server is started with — no live OAuth provider required.

test.describe('Authenticated header UI', () => {
  test.use({ storageState: 'e2e/fixtures/authenticated.json' });

  test('UserMenu with initials is visible when signed in', async ({ page }) => {
    await page.goto('/');
    // layout.tsx calls auth() server-side — valid session → renders UserMenu, not SignInButton
    await expect(page.getByRole('button', { name: /sign in/i })).not.toBeVisible();
    // UserMenu renders a button with aria-label "User menu for <name>"
    // auth-setup seeds name "Test User" → initials "TU"
    await expect(page.getByRole('button', { name: /user menu for test user/i })).toBeVisible();
  });

  test('sign-out action returns to unauthenticated state', async ({ page }) => {
    await page.goto('/');
    const menuButton = page.getByRole('button', { name: /user menu for test user/i });
    await expect(menuButton).toBeVisible();

    // Open the dropdown
    await menuButton.click();

    // Click Sign out and wait for the post-signout redirect back to /
    await Promise.all([
      page.waitForURL('/'),
      page.getByRole('button', { name: /sign out/i }).click(),
    ]);

    // After sign out, session cookie is cleared — layout renders SignInButton
    await expect(page.getByRole('button', { name: /sign in/i })).toBeVisible();
  });
});
