/* auto-generated by napi-rs — do not edit manually */

/** Information about the currently active (foreground) window. */
export interface ActiveWindowInfo {
  /** Process executable name (e.g. "Code", "chrome", "Photoshop"). */
  processName: string;
  /**
   * Window title or app display name.
   * On macOS: localizedName. On Windows: the window title string.
   */
  windowTitle: string;
  /**
   * macOS bundle identifier (e.g. "com.microsoft.VSCode").
   * undefined on Windows.
   */
  bundleId?: string;
}

/**
 * Returns information about the currently active (foreground) window,
 * or null if detection fails or the platform is unsupported.
 */
export declare function getActiveWindow(): ActiveWindowInfo | null;
